<a href="https://colab.research.google.com/github/Dsiddhart/Deep-lerning/blob/main/a%20neural%20network.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
import math

def sigmoid(x):
  y=1.0/(1+ math.exp(-x))
  return y

def activate(inputs,weights):
  h=0
  for x,w in zip(inputs,weights):
    h+=x*w

  return sigmoid(h)



if __name__ == "__main__":
  inputs=[.5,.3,.2]#list
  weights=[.4,.7,.2]
  output=activate(inputs,weights)
  print(output)

0.610639233949222


**Implementing a neural network**


In [13]:
import numpy as np

class MLP:

  def __init__(self,num_input=3,num_hlayer=[3,5],num_output=2):

    self.num_input=num_input;
    self.num_hlayer=num_hlayer;
    self.num_output=num_output;
    # no. of neurons in each layers
    layers_neurons=[self.num_input]+self.num_hlayer+[self.num_output];

    # initiate random weights

    self.weights=[]
    for i in range(len(layers_neurons)-1):
      w=np.random.rand(layers_neurons[i],layers_neurons[i+1])# (0,1)
      self.weights.append(w)

  def forward_propagate(self,inputs):
    activations=inputs
    print("no.of inputs in starting:{}".format(activations))
    for w in self.weights:
      # calculate net input
      print("no.of weights:{}".format(w))
      net_inputs=np.dot(activations,w)

      print("no.of net inputs:{}".format(net_inputs))

      # calculate the activations

      activations =self._sigmoid(net_inputs)
      print("no.of inputs after activation function:{}".format(activations))
    return activations

  def _sigmoid(self,x):
    return 1/(1+np.exp(-x))


if __name__=="__main__":

  # create an mlp
  mlp=MLP()
  #create some inputs
  inputs= np.random.rand(mlp.num_input)
  # perform forward prop

  outputs=mlp.forward_propagate(inputs)

  # print the result
  print("the network input is:{}".format(inputs))
  print("the network output is:{}".format(outputs))






no.of inputs in starting:[0.14078178 0.40869921 0.70319024]
no.of weights:[[0.6603802  0.97484058 0.9513426 ]
 [0.58624649 0.2956111  0.5551544 ]
 [0.68168455 0.06055743 0.71197572]]
no.of net inputs:[0.8119219  0.3006392  0.86147724]
no.of inputs after activation function:[0.6925189  0.57459877 0.7029692 ]
no.of weights:[[0.45015699 0.31952276 0.80474423 0.42446391 0.12716369]
 [0.07179001 0.67487445 0.0725651  0.6964972  0.53426536]
 [0.0440159  0.11405702 0.36324952 0.4264601  0.13363441]]
no.of net inputs:[0.38393449 0.68923615 0.85434962 0.99394403 0.48899235]
no.of inputs after activation function:[0.5948217  0.66579698 0.70147878 0.72986624 0.61986903]
no.of weights:[[0.94159949 0.64817376]
 [0.72310987 0.43552203]
 [0.14948997 0.68287782]
 [0.75093326 0.20144975]
 [0.43723054 0.73972636]]
no.of net inputs:[1.96549873 1.76010621]
no.of inputs after activation function:[0.87712681 0.85322296]
the network input is:[0.14078178 0.40869921 0.70319024]
the network output is:[0.8771268